[supervisord]
nodaemon=true
user=pol

[program:pol]
command=/workspace/pol
directory=/workspace
autostart=true
autorestart=true
stderr_logfile=/workspace/logs/pol.err.log
stdout_logfile=/workspace/logs/pol.out.log
user=pol
environment=HOME="/home/pol",USER="pol"

[program:api]
command=python3 /workspace/api/main.py
directory=/workspace/api
autostart=true
autorestart=true
stderr_logfile=/workspace/logs/api.err.log
stdout_logfile=/workspace/logs/api.out.log
user=pol
environment=PYTHONPATH="/workspace/api"